version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: LibiadaCore.sln
  verbosity: normal