//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TestChainAnalysis.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Answer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapSpaceOfValueString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapSpaceOfChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateAlphabetInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAlphabetOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkovChainInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkovChainOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback KRABInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback KRABOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback PhantomChainsInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback PhantomChainsOutputOperationCompleted;
        
        private System.Threading.SendOrPostCallback SegmentationInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback SegmentationOutputOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::TestChainAnalysis.Properties.Settings.Default.TestChainAnalysis_localhost_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateAlphabetInputCompletedEventHandler CreateAlphabetInputCompleted;
        
        /// <remarks/>
        public event CreateAlphabetOutputCompletedEventHandler CreateAlphabetOutputCompleted;
        
        /// <remarks/>
        public event CalculateInputCompletedEventHandler CalculateInputCompleted;
        
        /// <remarks/>
        public event CalculateOutputCompletedEventHandler CalculateOutputCompleted;
        
        /// <remarks/>
        public event MarkovChainInputCompletedEventHandler MarkovChainInputCompleted;
        
        /// <remarks/>
        public event MarkovChainOutputCompletedEventHandler MarkovChainOutputCompleted;
        
        /// <remarks/>
        public event KRABInputCompletedEventHandler KRABInputCompleted;
        
        /// <remarks/>
        public event KRABOutputCompletedEventHandler KRABOutputCompleted;
        
        /// <remarks/>
        public event PhantomChainsInputCompletedEventHandler PhantomChainsInputCompleted;
        
        /// <remarks/>
        public event PhantomChainsOutputCompletedEventHandler PhantomChainsOutputCompleted;
        
        /// <remarks/>
        public event SegmentationInputCompletedEventHandler SegmentationInputCompleted;
        
        /// <remarks/>
        public event SegmentationOutputCompletedEventHandler SegmentationOutputCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateAlphabetInput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateAlphabetInput(RequestFiles request) {
            object[] results = this.Invoke("CreateAlphabetInput", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAlphabetInputAsync(RequestFiles request) {
            this.CreateAlphabetInputAsync(request, null);
        }
        
        /// <remarks/>
        public void CreateAlphabetInputAsync(RequestFiles request, object userState) {
            if ((this.CreateAlphabetInputOperationCompleted == null)) {
                this.CreateAlphabetInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAlphabetInputOperationCompleted);
            }
            this.InvokeAsync("CreateAlphabetInput", new object[] {
                        request}, this.CreateAlphabetInputOperationCompleted, userState);
        }
        
        private void OnCreateAlphabetInputOperationCompleted(object arg) {
            if ((this.CreateAlphabetInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAlphabetInputCompleted(this, new CreateAlphabetInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateAlphabetOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnswerObjects CreateAlphabetOutput(string hash) {
            object[] results = this.Invoke("CreateAlphabetOutput", new object[] {
                        hash});
            return ((AnswerObjects)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAlphabetOutputAsync(string hash) {
            this.CreateAlphabetOutputAsync(hash, null);
        }
        
        /// <remarks/>
        public void CreateAlphabetOutputAsync(string hash, object userState) {
            if ((this.CreateAlphabetOutputOperationCompleted == null)) {
                this.CreateAlphabetOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAlphabetOutputOperationCompleted);
            }
            this.InvokeAsync("CreateAlphabetOutput", new object[] {
                        hash}, this.CreateAlphabetOutputOperationCompleted, userState);
        }
        
        private void OnCreateAlphabetOutputOperationCompleted(object arg) {
            if ((this.CreateAlphabetOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAlphabetOutputCompleted(this, new CreateAlphabetOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateInput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalculateInput(RequestFiles request) {
            object[] results = this.Invoke("CalculateInput", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateInputAsync(RequestFiles request) {
            this.CalculateInputAsync(request, null);
        }
        
        /// <remarks/>
        public void CalculateInputAsync(RequestFiles request, object userState) {
            if ((this.CalculateInputOperationCompleted == null)) {
                this.CalculateInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateInputOperationCompleted);
            }
            this.InvokeAsync("CalculateInput", new object[] {
                        request}, this.CalculateInputOperationCompleted, userState);
        }
        
        private void OnCalculateInputOperationCompleted(object arg) {
            if ((this.CalculateInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateInputCompleted(this, new CalculateInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnswerChain CalculateOutput(string hash) {
            object[] results = this.Invoke("CalculateOutput", new object[] {
                        hash});
            return ((AnswerChain)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateOutputAsync(string hash) {
            this.CalculateOutputAsync(hash, null);
        }
        
        /// <remarks/>
        public void CalculateOutputAsync(string hash, object userState) {
            if ((this.CalculateOutputOperationCompleted == null)) {
                this.CalculateOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateOutputOperationCompleted);
            }
            this.InvokeAsync("CalculateOutput", new object[] {
                        hash}, this.CalculateOutputOperationCompleted, userState);
        }
        
        private void OnCalculateOutputOperationCompleted(object arg) {
            if ((this.CalculateOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateOutputCompleted(this, new CalculateOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarkovChainInput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MarkovChainInput(RequestMarkovChain request) {
            object[] results = this.Invoke("MarkovChainInput", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MarkovChainInputAsync(RequestMarkovChain request) {
            this.MarkovChainInputAsync(request, null);
        }
        
        /// <remarks/>
        public void MarkovChainInputAsync(RequestMarkovChain request, object userState) {
            if ((this.MarkovChainInputOperationCompleted == null)) {
                this.MarkovChainInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkovChainInputOperationCompleted);
            }
            this.InvokeAsync("MarkovChainInput", new object[] {
                        request}, this.MarkovChainInputOperationCompleted, userState);
        }
        
        private void OnMarkovChainInputOperationCompleted(object arg) {
            if ((this.MarkovChainInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkovChainInputCompleted(this, new MarkovChainInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarkovChainOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnswerMarkovChain MarkovChainOutput(string hash) {
            object[] results = this.Invoke("MarkovChainOutput", new object[] {
                        hash});
            return ((AnswerMarkovChain)(results[0]));
        }
        
        /// <remarks/>
        public void MarkovChainOutputAsync(string hash) {
            this.MarkovChainOutputAsync(hash, null);
        }
        
        /// <remarks/>
        public void MarkovChainOutputAsync(string hash, object userState) {
            if ((this.MarkovChainOutputOperationCompleted == null)) {
                this.MarkovChainOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkovChainOutputOperationCompleted);
            }
            this.InvokeAsync("MarkovChainOutput", new object[] {
                        hash}, this.MarkovChainOutputOperationCompleted, userState);
        }
        
        private void OnMarkovChainOutputOperationCompleted(object arg) {
            if ((this.MarkovChainOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkovChainOutputCompleted(this, new MarkovChainOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KRABInput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KRABInput(RequestClusterization request) {
            object[] results = this.Invoke("KRABInput", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KRABInputAsync(RequestClusterization request) {
            this.KRABInputAsync(request, null);
        }
        
        /// <remarks/>
        public void KRABInputAsync(RequestClusterization request, object userState) {
            if ((this.KRABInputOperationCompleted == null)) {
                this.KRABInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKRABInputOperationCompleted);
            }
            this.InvokeAsync("KRABInput", new object[] {
                        request}, this.KRABInputOperationCompleted, userState);
        }
        
        private void OnKRABInputOperationCompleted(object arg) {
            if ((this.KRABInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KRABInputCompleted(this, new KRABInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KRABOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnswerClusterization KRABOutput(string hash) {
            object[] results = this.Invoke("KRABOutput", new object[] {
                        hash});
            return ((AnswerClusterization)(results[0]));
        }
        
        /// <remarks/>
        public void KRABOutputAsync(string hash) {
            this.KRABOutputAsync(hash, null);
        }
        
        /// <remarks/>
        public void KRABOutputAsync(string hash, object userState) {
            if ((this.KRABOutputOperationCompleted == null)) {
                this.KRABOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKRABOutputOperationCompleted);
            }
            this.InvokeAsync("KRABOutput", new object[] {
                        hash}, this.KRABOutputOperationCompleted, userState);
        }
        
        private void OnKRABOutputOperationCompleted(object arg) {
            if ((this.KRABOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KRABOutputCompleted(this, new KRABOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PhantomChainsInput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PhantomChainsInput(RequestPhantomChains request) {
            object[] results = this.Invoke("PhantomChainsInput", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PhantomChainsInputAsync(RequestPhantomChains request) {
            this.PhantomChainsInputAsync(request, null);
        }
        
        /// <remarks/>
        public void PhantomChainsInputAsync(RequestPhantomChains request, object userState) {
            if ((this.PhantomChainsInputOperationCompleted == null)) {
                this.PhantomChainsInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPhantomChainsInputOperationCompleted);
            }
            this.InvokeAsync("PhantomChainsInput", new object[] {
                        request}, this.PhantomChainsInputOperationCompleted, userState);
        }
        
        private void OnPhantomChainsInputOperationCompleted(object arg) {
            if ((this.PhantomChainsInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PhantomChainsInputCompleted(this, new PhantomChainsInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PhantomChainsOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnswerPhantomChains PhantomChainsOutput(string hash) {
            object[] results = this.Invoke("PhantomChainsOutput", new object[] {
                        hash});
            return ((AnswerPhantomChains)(results[0]));
        }
        
        /// <remarks/>
        public void PhantomChainsOutputAsync(string hash) {
            this.PhantomChainsOutputAsync(hash, null);
        }
        
        /// <remarks/>
        public void PhantomChainsOutputAsync(string hash, object userState) {
            if ((this.PhantomChainsOutputOperationCompleted == null)) {
                this.PhantomChainsOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPhantomChainsOutputOperationCompleted);
            }
            this.InvokeAsync("PhantomChainsOutput", new object[] {
                        hash}, this.PhantomChainsOutputOperationCompleted, userState);
        }
        
        private void OnPhantomChainsOutputOperationCompleted(object arg) {
            if ((this.PhantomChainsOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PhantomChainsOutputCompleted(this, new PhantomChainsOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SegmentationInput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SegmentationInput(RequestSegmentation request) {
            object[] results = this.Invoke("SegmentationInput", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SegmentationInputAsync(RequestSegmentation request) {
            this.SegmentationInputAsync(request, null);
        }
        
        /// <remarks/>
        public void SegmentationInputAsync(RequestSegmentation request, object userState) {
            if ((this.SegmentationInputOperationCompleted == null)) {
                this.SegmentationInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSegmentationInputOperationCompleted);
            }
            this.InvokeAsync("SegmentationInput", new object[] {
                        request}, this.SegmentationInputOperationCompleted, userState);
        }
        
        private void OnSegmentationInputOperationCompleted(object arg) {
            if ((this.SegmentationInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SegmentationInputCompleted(this, new SegmentationInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SegmentationOutput", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnswerSegmentation SegmentationOutput(string hash) {
            object[] results = this.Invoke("SegmentationOutput", new object[] {
                        hash});
            return ((AnswerSegmentation)(results[0]));
        }
        
        /// <remarks/>
        public void SegmentationOutputAsync(string hash) {
            this.SegmentationOutputAsync(hash, null);
        }
        
        /// <remarks/>
        public void SegmentationOutputAsync(string hash, object userState) {
            if ((this.SegmentationOutputOperationCompleted == null)) {
                this.SegmentationOutputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSegmentationOutputOperationCompleted);
            }
            this.InvokeAsync("SegmentationOutput", new object[] {
                        hash}, this.SegmentationOutputOperationCompleted, userState);
        }
        
        private void OnSegmentationOutputOperationCompleted(object arg) {
            if ((this.SegmentationOutputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SegmentationOutputCompleted(this, new SegmentationOutputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestFiles : Request {
        
        private ActionType actionField;
        
        private File filesField;
        
        /// <remarks/>
        public ActionType Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public File Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActionType : TypeBase {
        
        private LinkUp linkUpField;
        
        private int blockSizeField;
        
        /// <remarks/>
        public LinkUp LinkUp {
            get {
                return this.linkUpField;
            }
            set {
                this.linkUpField = value;
            }
        }
        
        /// <remarks/>
        public int BlockSize {
            get {
                return this.blockSizeField;
            }
            set {
                this.blockSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LinkUp {
        
        /// <remarks/>
        Start,
        
        /// <remarks/>
        End,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class TypeBase {
        
        private string nameField;
        
        private string mIMEField;
        
        private long sizeField;
        
        private int hashCodeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string MIME {
            get {
                return this.mIMEField;
            }
            set {
                this.mIMEField = value;
            }
        }
        
        /// <remarks/>
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public int HashCode {
            get {
                return this.hashCodeField;
            }
            set {
                this.hashCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapCluster {
        
        private int[] itemsField;
        
        /// <remarks/>
        public int[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapClusterizationResult {
        
        private SoapCluster[] clustersField;
        
        private double qualityField;
        
        /// <remarks/>
        public SoapCluster[] Clusters {
            get {
                return this.clustersField;
            }
            set {
                this.clustersField = value;
            }
        }
        
        /// <remarks/>
        public double Quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapClusterizationVaraints {
        
        private SoapClusterizationResult[] variantsField;
        
        /// <remarks/>
        public SoapClusterizationResult[] Variants {
            get {
                return this.variantsField;
            }
            set {
                this.variantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnswerSegmentation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnswerPhantomChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnswerClusterization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnswerMarkovChain))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnswerChain))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnswerObjects))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Answer {
        
        private ErrorType errorField;
        
        /// <remarks/>
        public ErrorType Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorType : TypeBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerSegmentation : Answer {
        
        private SoapChainOfChains chainField;
        
        private double bestLevelField;
        
        private double bestDeltaField;
        
        private double theoryVolumeField;
        
        /// <remarks/>
        public SoapChainOfChains Chain {
            get {
                return this.chainField;
            }
            set {
                this.chainField = value;
            }
        }
        
        /// <remarks/>
        public double BestLevel {
            get {
                return this.bestLevelField;
            }
            set {
                this.bestLevelField = value;
            }
        }
        
        /// <remarks/>
        public double BestDelta {
            get {
                return this.bestDeltaField;
            }
            set {
                this.bestDeltaField = value;
            }
        }
        
        /// <remarks/>
        public double TheoryVolume {
            get {
                return this.theoryVolumeField;
            }
            set {
                this.theoryVolumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapChainOfChains : SoapChainWithCharacteristicOfChains {
        
        private SoapUniformChainOfChains[] uniformChainsField;
        
        /// <remarks/>
        public SoapUniformChainOfChains[] UniformChains {
            get {
                return this.uniformChainsField;
            }
            set {
                this.uniformChainsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapUniformChainOfChains : SoapChainWithCharacteristicOfChains {
        
        private SoapPhantomMessageOfChains messageField;
        
        /// <remarks/>
        public SoapPhantomMessageOfChains Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapPhantomMessageOfChains {
        
        private SoapChainOfValueString[] messagesField;
        
        /// <remarks/>
        public SoapChainOfValueString[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapChainOfValueString : SoapChainWithCharacteristicOfValueString {
        
        private SoapUniformChainOfValueString[] uniformChainsField;
        
        /// <remarks/>
        public SoapUniformChainOfValueString[] UniformChains {
            get {
                return this.uniformChainsField;
            }
            set {
                this.uniformChainsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapUniformChainOfValueString : SoapChainWithCharacteristicOfValueString {
        
        private SoapValueString messageField;
        
        /// <remarks/>
        public SoapValueString Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapValueString {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapUniformChainOfValueString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainOfValueString))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapChainWithCharacteristicOfValueString : SoapBaseChainOfValueString {
        
        private SoapCharacteristic[] characteristicsField;
        
        private SoapFrequencyList startIntervalsField;
        
        private SoapFrequencyList commonIntervalsField;
        
        private SoapFrequencyList endIntervalField;
        
        /// <remarks/>
        public SoapCharacteristic[] Characteristics {
            get {
                return this.characteristicsField;
            }
            set {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        public SoapFrequencyList StartIntervals {
            get {
                return this.startIntervalsField;
            }
            set {
                this.startIntervalsField = value;
            }
        }
        
        /// <remarks/>
        public SoapFrequencyList CommonIntervals {
            get {
                return this.commonIntervalsField;
            }
            set {
                this.commonIntervalsField = value;
            }
        }
        
        /// <remarks/>
        public SoapFrequencyList EndInterval {
            get {
                return this.endIntervalField;
            }
            set {
                this.endIntervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapCharacteristic {
        
        private double startField;
        
        private double endField;
        
        private double bothField;
        
        private string typeField;
        
        /// <remarks/>
        public double Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public double End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public double Both {
            get {
                return this.bothField;
            }
            set {
                this.bothField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapFrequencyList {
        
        private SoapFrequencyListItem[] elementsField;
        
        /// <remarks/>
        public SoapFrequencyListItem[] Elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapFrequencyListItem {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainWithCharacteristicOfValueString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapUniformChainOfValueString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainOfValueString))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapBaseChainOfValueString : SoapSpaceOfValueString {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapBaseChainOfValueString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainWithCharacteristicOfValueString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapUniformChainOfValueString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainOfValueString))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapSpaceOfValueString {
        
        private long[] buildingField;
        
        private SoapAlphabetOfValueString alphabetField;
        
        private SoapDimension[] dimensionsField;
        
        /// <remarks/>
        public long[] Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        public SoapAlphabetOfValueString Alphabet {
            get {
                return this.alphabetField;
            }
            set {
                this.alphabetField = value;
            }
        }
        
        /// <remarks/>
        public SoapDimension[] Dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapAlphabetOfValueString {
        
        private SoapValueString[] elementsField;
        
        /// <remarks/>
        public SoapValueString[] Elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapDimension {
        
        private long maxField;
        
        private long minField;
        
        /// <remarks/>
        public long Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        public long Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapUniformChainOfChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainOfChains))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapChainWithCharacteristicOfChains : SoapBaseChainOfChains {
        
        private SoapCharacteristic[] characteristicsField;
        
        private SoapFrequencyList startIntervalsField;
        
        private SoapFrequencyList commonIntervalsField;
        
        private SoapFrequencyList endIntervalField;
        
        /// <remarks/>
        public SoapCharacteristic[] Characteristics {
            get {
                return this.characteristicsField;
            }
            set {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        public SoapFrequencyList StartIntervals {
            get {
                return this.startIntervalsField;
            }
            set {
                this.startIntervalsField = value;
            }
        }
        
        /// <remarks/>
        public SoapFrequencyList CommonIntervals {
            get {
                return this.commonIntervalsField;
            }
            set {
                this.commonIntervalsField = value;
            }
        }
        
        /// <remarks/>
        public SoapFrequencyList EndInterval {
            get {
                return this.endIntervalField;
            }
            set {
                this.endIntervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainWithCharacteristicOfChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapUniformChainOfChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainOfChains))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapBaseChainOfChains : SoapSpaceOfChains {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapBaseChainOfChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainWithCharacteristicOfChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapUniformChainOfChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoapChainOfChains))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapSpaceOfChains {
        
        private long[] buildingField;
        
        private SoapAlphabetOfChains alphabetField;
        
        private SoapDimension[] dimensionsField;
        
        /// <remarks/>
        public long[] Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        public SoapAlphabetOfChains Alphabet {
            get {
                return this.alphabetField;
            }
            set {
                this.alphabetField = value;
            }
        }
        
        /// <remarks/>
        public SoapDimension[] Dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapAlphabetOfChains {
        
        private SoapPhantomMessageOfChains[] elementsField;
        
        /// <remarks/>
        public SoapPhantomMessageOfChains[] Elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerPhantomChains : Answer {
        
        private SoapChainOfChains[] chainsField;
        
        /// <remarks/>
        public SoapChainOfChains[] Chains {
            get {
                return this.chainsField;
            }
            set {
                this.chainsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerClusterization : Answer {
        
        private SoapClusterizationVaraints variantField;
        
        /// <remarks/>
        public SoapClusterizationVaraints Variant {
            get {
                return this.variantField;
            }
            set {
                this.variantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerMarkovChain : Answer {
        
        private SoapChainOfChains[] chainsField;
        
        /// <remarks/>
        public SoapChainOfChains[] Chains {
            get {
                return this.chainsField;
            }
            set {
                this.chainsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerChain : Answer {
        
        private SoapChainOfChains chainField;
        
        /// <remarks/>
        public SoapChainOfChains Chain {
            get {
                return this.chainField;
            }
            set {
                this.chainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerObjects : Answer {
        
        private SoapAlphabetOfChains alphabetField;
        
        /// <remarks/>
        public SoapAlphabetOfChains Alphabet {
            get {
                return this.alphabetField;
            }
            set {
                this.alphabetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapDataCharacteristic {
        
        private string keyField;
        
        private double valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapDataObject {
        
        private int idField;
        
        private SoapDataCharacteristic[] vaultField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public SoapDataCharacteristic[] vault {
            get {
                return this.vaultField;
            }
            set {
                this.vaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapDataTable {
        
        private SoapDataObject[] objectsField;
        
        /// <remarks/>
        public SoapDataObject[] Objects {
            get {
                return this.objectsField;
            }
            set {
                this.objectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class File {
        
        private FileType fileTypeField;
        
        private string dataField;
        
        private string typeField;
        
        /// <remarks/>
        public FileType FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileType : TypeBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestSegmentation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestPhantomChains))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestClusterization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestMarkovChain))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestFiles))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Request {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestSegmentation : Request {
        
        private double balanceFactorField;
        
        private File filesField;
        
        private int startLengthField;
        
        private LinkUp linkField;
        
        private Method calculateFrequenceMethodField;
        
        private double rightValueField;
        
        private double epsField;
        
        /// <remarks/>
        public double BalanceFactor {
            get {
                return this.balanceFactorField;
            }
            set {
                this.balanceFactorField = value;
            }
        }
        
        /// <remarks/>
        public File Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
            }
        }
        
        /// <remarks/>
        public int StartLength {
            get {
                return this.startLengthField;
            }
            set {
                this.startLengthField = value;
            }
        }
        
        /// <remarks/>
        public LinkUp Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public Method CalculateFrequenceMethod {
            get {
                return this.calculateFrequenceMethodField;
            }
            set {
                this.calculateFrequenceMethodField = value;
            }
        }
        
        /// <remarks/>
        public double RightValue {
            get {
                return this.rightValueField;
            }
            set {
                this.rightValueField = value;
            }
        }
        
        /// <remarks/>
        public double Eps {
            get {
                return this.epsField;
            }
            set {
                this.epsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Method {
        
        /// <remarks/>
        Convoluted,
        
        /// <remarks/>
        NotConvoluted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestPhantomChains : Request {
        
        private GeneratorType generatorField;
        
        private int generateChainsCountField;
        
        private SoapChainOfChains chainField;
        
        /// <remarks/>
        public GeneratorType Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        public int GenerateChainsCount {
            get {
                return this.generateChainsCountField;
            }
            set {
                this.generateChainsCountField = value;
            }
        }
        
        /// <remarks/>
        public SoapChainOfChains Chain {
            get {
                return this.chainField;
            }
            set {
                this.chainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum GeneratorType {
        
        /// <remarks/>
        SimpleGenerator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestClusterization : Request {
        
        private SoapDataTable dataTableField;
        
        private MethodClusterization methodField;
        
        private int clusterCountField;
        
        /// <remarks/>
        public SoapDataTable DataTable {
            get {
                return this.dataTableField;
            }
            set {
                this.dataTableField = value;
            }
        }
        
        /// <remarks/>
        public MethodClusterization Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public int ClusterCount {
            get {
                return this.clusterCountField;
            }
            set {
                this.clusterCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MethodClusterization {
        
        /// <remarks/>
        Simple,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestMarkovChain : Request {
        
        private GeneratorType generatorField;
        
        private GeneratingMethod methodField;
        
        private TeachingMethod preChangesField;
        
        private int lengthField;
        
        private int generateChainsCountField;
        
        private int markovChainRangField;
        
        private SoapChainOfChains chainField;
        
        /// <remarks/>
        public GeneratorType Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        public GeneratingMethod Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public TeachingMethod PreChanges {
            get {
                return this.preChangesField;
            }
            set {
                this.preChangesField = value;
            }
        }
        
        /// <remarks/>
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public int GenerateChainsCount {
            get {
                return this.generateChainsCountField;
            }
            set {
                this.generateChainsCountField = value;
            }
        }
        
        /// <remarks/>
        public int MarkovChainRang {
            get {
                return this.markovChainRangField;
            }
            set {
                this.markovChainRangField = value;
            }
        }
        
        /// <remarks/>
        public SoapChainOfChains Chain {
            get {
                return this.chainField;
            }
            set {
                this.chainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum GeneratingMethod {
        
        /// <remarks/>
        StaticUniform,
        
        /// <remarks/>
        StaticNotUniform,
        
        /// <remarks/>
        DynamicUniform,
        
        /// <remarks/>
        DynamicNotUniform,
        
        /// <remarks/>
        Random,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TeachingMethod {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Cycle,
        
        /// <remarks/>
        CycleBuilding,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateAlphabetInputCompletedEventHandler(object sender, CreateAlphabetInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAlphabetInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAlphabetInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateAlphabetOutputCompletedEventHandler(object sender, CreateAlphabetOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAlphabetOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAlphabetOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnswerObjects Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnswerObjects)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CalculateInputCompletedEventHandler(object sender, CalculateInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CalculateOutputCompletedEventHandler(object sender, CalculateOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnswerChain Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnswerChain)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MarkovChainInputCompletedEventHandler(object sender, MarkovChainInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkovChainInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarkovChainInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MarkovChainOutputCompletedEventHandler(object sender, MarkovChainOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkovChainOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarkovChainOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnswerMarkovChain Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnswerMarkovChain)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KRABInputCompletedEventHandler(object sender, KRABInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KRABInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KRABInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KRABOutputCompletedEventHandler(object sender, KRABOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KRABOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KRABOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnswerClusterization Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnswerClusterization)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PhantomChainsInputCompletedEventHandler(object sender, PhantomChainsInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PhantomChainsInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PhantomChainsInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PhantomChainsOutputCompletedEventHandler(object sender, PhantomChainsOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PhantomChainsOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PhantomChainsOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnswerPhantomChains Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnswerPhantomChains)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SegmentationInputCompletedEventHandler(object sender, SegmentationInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SegmentationInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SegmentationInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SegmentationOutputCompletedEventHandler(object sender, SegmentationOutputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SegmentationOutputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SegmentationOutputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnswerSegmentation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnswerSegmentation)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591